apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-connector
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: whatsapp-connector
          image: harbor.e-dani.com/homelab/whatsappmcp-whatsapp-connector:v1.3.36@sha256:e0b56c344f886aa45867dba1078af85cde5569692b1256b84c72c9a48281f600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-connector-professional
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: whatsapp-connector-professional
          image: harbor.e-dani.com/homelab/whatsappmcp-whatsapp-connector:v1.3.36@sha256:e0b56c344f886aa45867dba1078af85cde5569692b1256b84c72c9a48281f600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-connector
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: instagram-connector
          image: harbor.e-dani.com/homelab/whatsappmcp-instagram-connector:v1.3.12@sha256:33d980dc270af8a6942a762c122428712250714e35003f7435e7f47d2f91aa07
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-connector
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: telegram-connector
          image: harbor.e-dani.com/homelab/whatsappmcp-telegram-connector:v1.3.37@sha256:d2ab11bbb894be2cd1028abc9efdc4f14d2c59a0fe9897b4394b23fe9dc911ce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: mcp-server
          image: harbor.e-dani.com/homelab/whatsappmcp-mcp-server:v1.3.34@sha256:df01decb558201b9c0267505cb55571e9700824d90a01a0a4a69a4222489e3ab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-sync
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: telegram-sync
          image: harbor.e-dani.com/homelab/whatsappmcp-telegram-sync:v1.3.38@sha256:37f5b886685b0682bdfa070df67d98cf76e2963e0c61406b634330e72d31bc06
