/**
 * WhatsApp polls (fase 3 / PR-7, ported from the NAS fork's poll-votes.ts and
 * adapted to prod) — the pure part: poll definitions, request validation and
 * the vote crypto. No socket, no DB (poll-event-store.ts is the DB side).
 *
 * Baileys 7.0.0-rc13 sends poll CREATION (`sendMessage({ poll })`) but has no
 * vote helper: `generateWAMessageContent` has no `pollUpdateMessage` branch
 * and the inbound vote decryption in `processMessage` is commented out
 * upstream. It does export every primitive (`decryptPollVote`,
 * `aesEncryptGCM`, `hmacSign`, `sha256`, `proto`), so both directions are
 * built here.
 *
 * The scheme (same for event responses, see event-responses.ts): the poll's
 * `messageContextInfo.messageSecret` (32 bytes, generated by the creator) is
 * the base key; key = HKDF(secret, info = pollId ‖ creatorJid ‖ voterJid ‖
 * "Poll Vote"), AES-256-GCM with aad = pollId \0 voterJid, the plaintext a
 * PollVoteMessage with the SHA-256 of every selected option name. An empty
 * selection is a retracted vote.
 *
 * Identities (the part WhatsApp's LID migration made fragile): the jids in
 * the key derivation are the ones the chat is ADDRESSED with — a LID-addressed
 * group signs with LIDs, a phone-addressed one with phone jids. whatsmeow
 * (EncryptPollVote) votes with its own LID unless the poll's sender is a
 * phone jid; we follow the same rule when voting. When decrypting we try
 * every identity we know for creator and voter (PN and LID): AES-GCM
 * authenticates, so a wrong pair fails and never yields a wrong vote.
 */
import { randomBytes } from 'node:crypto';
import { CapabilityError } from './whatsapp-capabilities';
import {
  aesEncryptGCM,
  decryptPollVote,
  getKeyAuthor,
  hmacSign,
  isJidGroup,
  jidNormalizedUser,
  normalizeMessageContent,
  proto,
  sha256,
} from '@whiskeysockets/baileys';
import type { AnyMessageContent, WAMessageContent, WAMessageKey } from '@whiskeysockets/baileys';

export const POLL_QUESTION_MAX_LENGTH = 255;
export const POLL_OPTION_MAX_LENGTH = 100;
export const POLL_MIN_OPTIONS = 2;
export const POLL_MAX_OPTIONS = 12;

/** A request the connector refuses before anything reaches WhatsApp (400 invalid_request). */
export class PollEventInputError extends Error {
  readonly status = 400;
  readonly failureClass = 'invalid_request';
  readonly details?: Record<string, unknown>;

  constructor(message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = 'PollEventInputError';
    this.details = details;
  }
}

export interface PollDefinition {
  question: string;
  options: string[];
  /** 0 = any number of options (WhatsApp's "allow multiple answers"); 1 = single choice. */
  selectableCount: number;
}

export interface ValidatedPoll {
  name: string;
  options: string[];
  selectableCount: number;
}

// ---------------------------------------------------------------------------
// Reading polls
// ---------------------------------------------------------------------------

type AnyContent = proto.IMessage | null | undefined;

/** The poll creation of a message: V1/V2/V3/V5, V4 (future-proof wrapper), inside ephemeral/view-once. */
export function pollCreationOf(
  message: AnyContent
): proto.Message.IPollCreationMessage | undefined {
  const content = normalizeMessageContent(message as WAMessageContent | undefined);
  if (!content) return undefined;
  const direct =
    content.pollCreationMessage ||
    content.pollCreationMessageV2 ||
    content.pollCreationMessageV3 ||
    content.pollCreationMessageV5;
  if (direct) return direct;
  const inner = content.pollCreationMessageV4?.message;
  return inner && inner !== message ? pollCreationOf(inner) : undefined;
}

/** Question, options and selectable count of a poll message; null when it is not one. */
export function parsePollDefinition(message: AnyContent): PollDefinition | null {
  const creation = pollCreationOf(message);
  if (!creation) return null;
  const options = (creation.options || [])
    .map(option => (typeof option?.optionName === 'string' ? option.optionName : ''))
    .filter(name => name.length > 0);
  if (!options.length) return null;
  const raw = Number(creation.selectableOptionsCount ?? 0);
  const selectableCount =
    Number.isFinite(raw) && raw >= 1 ? Math.min(Math.floor(raw), options.length) : 0;
  return { question: String(creation.name || ''), options, selectableCount };
}

function bytes(value: unknown): Uint8Array | null {
  if (value instanceof Uint8Array) return value;
  if (typeof value === 'string' && value) return new Uint8Array(Buffer.from(value, 'base64'));
  if (Array.isArray(value) && value.every(n => typeof n === 'number')) return new Uint8Array(value);
  const tagged = value as { type?: unknown; data?: unknown } | null;
  if (tagged && tagged.type === 'Buffer' && Array.isArray(tagged.data)) {
    return new Uint8Array(tagged.data as number[]);
  }
  return null;
}

/**
 * The 32-byte messageSecret of a poll/event creation message (the encKey of
 * its votes / responses): top level or inside a wrapper. null when absent —
 * the message was stored without it (before PR-1) or WhatsApp never sent it.
 */
export function messageSecretOf(message: AnyContent): Uint8Array | null {
  const candidates = [
    (message as proto.IMessage | undefined)?.messageContextInfo?.messageSecret,
    normalizeMessageContent(message as WAMessageContent | undefined)?.messageContextInfo
      ?.messageSecret,
  ];
  for (const candidate of candidates) {
    const secret = bytes(candidate);
    if (secret && secret.length === 32) return secret;
  }
  return null;
}

/** Hex SHA-256 of an option name — what a vote carries for each selected option. */
export function optionHash(name: string): string {
  return Buffer.from(sha256(Buffer.from(name))).toString('hex');
}

/** Selected hashes → option names of the poll; hashes of no known option are kept apart. */
export function selectedOptionNames(
  definition: PollDefinition | null,
  hashes: string[]
): { names: string[]; unknown: string[] } {
  const byHash = new Map((definition?.options || []).map(name => [optionHash(name), name]));
  const names: string[] = [];
  const unknown: string[] = [];
  for (const hash of hashes) {
    const name = byHash.get(hash);
    if (name !== undefined) {
      if (!names.includes(name)) names.push(name);
    } else unknown.push(hash);
  }
  return { names, unknown };
}

// ---------------------------------------------------------------------------
// Request validation (before anything is sent)
// ---------------------------------------------------------------------------

/**
 * A poll to send: the limits of the official client, trimmed. An empty or
 * repeated option is refused rather than dropped (voters would otherwise see
 * a list that is not the one written). selectableCount: 0 (default) = any
 * number, 1 = single choice, up to the number of options.
 */
export function validatePollInput(input: {
  name: unknown;
  options: unknown;
  selectableCount?: unknown;
}): ValidatedPoll {
  const name = typeof input.name === 'string' ? input.name.trim() : '';
  if (!name) throw new PollEventInputError('A poll needs a question (name)', { field: 'name' });
  if (name.length > POLL_QUESTION_MAX_LENGTH) {
    throw new PollEventInputError(
      `The question is longer than ${POLL_QUESTION_MAX_LENGTH} characters`,
      { field: 'name', maxLength: POLL_QUESTION_MAX_LENGTH }
    );
  }
  if (!Array.isArray(input.options)) {
    throw new PollEventInputError('options must be a list of option names', { field: 'options' });
  }
  if (input.options.length < POLL_MIN_OPTIONS || input.options.length > POLL_MAX_OPTIONS) {
    throw new PollEventInputError(
      `A poll needs between ${POLL_MIN_OPTIONS} and ${POLL_MAX_OPTIONS} options`,
      {
        field: 'options',
        min: POLL_MIN_OPTIONS,
        max: POLL_MAX_OPTIONS,
        given: input.options.length,
      }
    );
  }
  const options = input.options.map((value: unknown, index: number) => {
    const option = typeof value === 'string' ? value.trim() : '';
    if (!option) {
      throw new PollEventInputError(`Option ${index + 1} is empty or not text`, {
        field: 'options',
        index,
      });
    }
    if (option.length > POLL_OPTION_MAX_LENGTH) {
      throw new PollEventInputError(
        `Option ${index + 1} is longer than ${POLL_OPTION_MAX_LENGTH} characters`,
        { field: 'options', index, maxLength: POLL_OPTION_MAX_LENGTH }
      );
    }
    return option;
  });
  if (new Set(options).size !== options.length) {
    throw new PollEventInputError('Poll options cannot repeat', { field: 'options' });
  }
  const raw = input.selectableCount;
  const selectableCount = raw === undefined || raw === null ? 0 : Number(raw);
  if (
    !Number.isInteger(selectableCount) ||
    selectableCount < 0 ||
    selectableCount > options.length
  ) {
    throw new PollEventInputError(
      `selectableCount must be an integer from 0 (any) to ${options.length}`,
      { field: 'selectableCount', max: options.length }
    );
  }
  return { name, options, selectableCount };
}

/** Baileys content of a validated poll (it adds the messageSecret itself). */
export function buildPollContent(poll: ValidatedPoll): AnyMessageContent {
  return {
    poll: { name: poll.name, values: poll.options, selectableCount: poll.selectableCount },
  } as AnyMessageContent;
}

/**
 * The options of a vote: exact names of the poll (never trimmed — WhatsApp
 * hashes the exact string), no repeats, at most selectableCount; [] retracts.
 */
export function validatePollSelection(definition: PollDefinition, requested: unknown): string[] {
  const refuse = (message: string, extra: Record<string, unknown> = {}): never => {
    throw new PollEventInputError(message, { validOptions: definition.options, ...extra });
  };
  if (!Array.isArray(requested)) refuse('options must be a list of option names ([] retracts)');
  const names = requested as unknown[];
  if (names.some(name => typeof name !== 'string' || !name)) {
    refuse('options must be non-empty strings');
  }
  const exact = names as string[];
  if (new Set(exact).size !== exact.length) refuse('options must not repeat an option');
  const unknown = exact.filter(name => !definition.options.includes(name));
  if (unknown.length) refuse(`Unknown poll option: ${JSON.stringify(unknown[0])}`, { unknown });
  const max =
    definition.selectableCount >= 1 ? definition.selectableCount : definition.options.length;
  if (exact.length > max)
    refuse(`This poll allows at most ${max} option(s)`, { maxSelectable: max });
  return exact;
}

// ---------------------------------------------------------------------------
// Identities
// ---------------------------------------------------------------------------

/** This account's own user jids (@s.whatsapp.net / @lid), normalised. */
export interface OwnIdentity {
  pn: string | null;
  lid: string | null;
}

const USER_JID = /^\d+(?::\d+)?@(?:s\.whatsapp\.net|c\.us|lid|hosted|hosted\.lid)$/;

/** A user jid as the crypto uses it (no device, @c.us → @s.whatsapp.net); null otherwise. */
export function cryptoUserJid(jid: string | null | undefined): string | null {
  if (!jid || !USER_JID.test(jid)) return null;
  const normalized = jidNormalizedUser(jid);
  return normalized.endsWith('@s.whatsapp.net') || normalized.endsWith('@lid') ? normalized : null;
}

function unique(jids: Array<string | null | undefined>): string[] {
  const out: string[] = [];
  for (const jid of jids) {
    const user = cryptoUserJid(jid);
    if (user && !out.includes(user)) out.push(user);
  }
  return out;
}

/**
 * Every identity the author of the message with this key may have signed
 * with: ours when fromMe; else the participant (group) or the chat (1:1), as
 * addressed first, then its alternate (PN ↔ LID) when Baileys carried it.
 */
export function keyAuthorCandidates(
  key: WAMessageKey | null | undefined,
  own: OwnIdentity
): string[] {
  if (!key) return [];
  if (key.fromMe) return unique([own.lid, own.pn]);
  const group = !!key.remoteJid && !!isJidGroup(key.remoteJid);
  return group
    ? unique([key.participant, key.participantAlt])
    : unique([key.remoteJid, key.remoteJidAlt]);
}

/**
 * The (creator, voter) pair to sign OUR vote / response with. `lidAddressed`
 * says how the chat addresses people (group addressingMode, or a 1:1 chat
 * with a @lid); it decides our identity for a poll of ours. For someone
 * else's poll the creator is the sender as addressed and we vote with our LID
 * unless that sender is a phone jid (whatsmeow's rule).
 */
export function pollSigningPair(
  creationKey: WAMessageKey,
  own: OwnIdentity,
  lidAddressed: boolean
): { creator: string; voter: string } | null {
  const ownIn = (lid: boolean): string | null => (lid ? own.lid || own.pn : own.pn || own.lid);
  if (creationKey.fromMe) {
    const me = ownIn(lidAddressed);
    return me ? { creator: me, voter: me } : null;
  }
  const group = !!creationKey.remoteJid && !!isJidGroup(creationKey.remoteJid);
  const creator = cryptoUserJid(group ? creationKey.participant : creationKey.remoteJid);
  if (!creator) return null;
  const voter = ownIn(creator.endsWith('@lid'));
  return voter ? { creator, voter } : null;
}

// ---------------------------------------------------------------------------
// Vote crypto
// ---------------------------------------------------------------------------

function secretKey(
  secret: Uint8Array,
  messageId: string,
  creator: string,
  modifier: string,
  useCase: 'Poll Vote' | 'Event Response'
): Buffer {
  const info = Buffer.concat([
    Buffer.from(messageId),
    Buffer.from(creator),
    Buffer.from(modifier),
    Buffer.from(useCase),
    new Uint8Array([1]),
  ]);
  const prk = hmacSign(Buffer.from(secret), new Uint8Array(32), 'sha256');
  return hmacSign(info, prk, 'sha256');
}

/** Exported for event-responses.ts: the same derivation with another use case. */
export function encryptMessageSecret(input: {
  secret: Uint8Array;
  messageId: string;
  creator: string;
  modifier: string;
  useCase: 'Poll Vote' | 'Event Response';
  plaintext: Uint8Array;
  iv?: Uint8Array;
}): { encPayload: Uint8Array; encIv: Uint8Array } {
  const iv = input.iv ?? new Uint8Array(randomBytes(12));
  const key = secretKey(
    input.secret,
    input.messageId,
    input.creator,
    input.modifier,
    input.useCase
  );
  const aad = Buffer.from(`${input.messageId}\u0000${input.modifier}`);
  return { encPayload: aesEncryptGCM(input.plaintext, key, iv, aad), encIv: iv };
}

export interface PollVoteBuild {
  /** Key of the poll creation message (as stored); its id is the poll id. */
  creationKey: WAMessageKey;
  secret: Uint8Array;
  creator: string;
  voter: string;
  /** Exact option names; [] = retract. */
  options: string[];
  senderTimestampMs: number;
  iv?: Uint8Array;
}

/** The pollUpdateMessage of our vote (what WhatsApp's own clients send). */
function buildProductionPollVoteContent(input: PollVoteBuild): WAMessageContent {
  const pollId = String(input.creationKey.id || '');
  if (!pollId) throw new Error('poll creation key without id');
  const plaintext = proto.Message.PollVoteMessage.encode({
    selectedOptions: input.options.map(name => new Uint8Array(sha256(Buffer.from(name)))),
  }).finish();
  const vote = encryptMessageSecret({
    secret: input.secret,
    messageId: pollId,
    creator: input.creator,
    modifier: input.voter,
    useCase: 'Poll Vote',
    plaintext,
    iv: input.iv,
  });
  const group = !!input.creationKey.remoteJid && !!isJidGroup(input.creationKey.remoteJid);
  return {
    pollUpdateMessage: {
      pollCreationMessageKey: {
        remoteJid: input.creationKey.remoteJid,
        fromMe: !!input.creationKey.fromMe,
        id: pollId,
        ...(group ? { participant: input.creator } : {}),
      },
      vote,
      senderTimestampMs: input.senderTimestampMs,
    },
  };
}

export interface DecryptedPollVote {
  /** Hex SHA-256 of each selected option ([] = retracted). */
  hashes: string[];
  creator: string;
  voter: string;
}

/**
 * Decrypt a vote trying every (creator, voter) identity pair. null when none
 * authenticates (wrong secret, unknown identity) — never throws.
 */
export function decryptPollVoteWith(
  vote: proto.Message.IPollEncValue | null | undefined,
  context: { pollId: string; secret: Uint8Array; creators: string[]; voters: string[] }
): DecryptedPollVote | null {
  const encPayload = bytes(vote?.encPayload);
  const encIv = bytes(vote?.encIv);
  if (!encPayload || !encIv || !context.pollId) return null;
  for (const creator of context.creators) {
    for (const voter of context.voters) {
      try {
        const decrypted = decryptPollVote(
          { encPayload, encIv },
          {
            pollCreatorJid: creator,
            pollMsgId: context.pollId,
            pollEncKey: context.secret,
            voterJid: voter,
          }
        );
        return {
          hashes: (decrypted.selectedOptions || []).map(option =>
            Buffer.from(option).toString('hex')
          ),
          creator,
          voter,
        };
      } catch {
        // Not this pair: try the next identity.
      }
    }
  }
  return null;
}

/** ms of a protobuf int64 (number | Long | string); undefined when absent or not positive. */
export function int64Ms(value: unknown): number | undefined {
  if (value === null || value === undefined) return undefined;
  if (typeof value === 'number') return Number.isFinite(value) && value > 0 ? value : undefined;
  if (typeof value === 'bigint') return int64Ms(Number(value));
  if (typeof value === 'string') return int64Ms(Number(value));
  const long = value as { toNumber?: () => number; low?: number; high?: number };
  if (typeof long.toNumber === 'function') return int64Ms(long.toNumber());
  if (typeof long.low === 'number') return int64Ms((long.high || 0) * 2 ** 32 + (long.low >>> 0));
  return undefined;
}

/**
 * WhatsApp poll voting on Baileys 7.0.0-rc13.
 *
 * rc13 ships poll CREATION (`sendMessage({ poll })`) but no vote helper:
 * `generateWAMessageContent` has no `pollUpdateMessage` branch, the automatic
 * inbound-vote decryption in `processMessage` is commented out upstream, and
 * there is no `getPollVotes`-style retrieval. What the library does export is
 * every primitive needed to do it ourselves: `decryptPollVote` (the exact
 * HMAC/AES-GCM scheme WA uses), `aesEncryptGCM`, `hmacSign`, `sha256`,
 * `getKeyAuthor`, `proto`, and `generateWAMessageFromContent`.
 *
 * Vote identity caveat we cannot verify offline: `getKeyAuthor` prefers the
 * `*Alt` (LID) fields, and WA validates a vote hash against the sender
 * identity the signer used. We sign with the same normalized self JID that
 * Baileys' own inbound path (and therefore our aggregation) uses, so our own
 * votes are self-consistent. Cross-device hash acceptance must be confirmed
 * with a live 1:1 vote; see connectors/whatsapp-web README notes.
 */

export interface PollCreationDetails {
  question: string;
  options: string[];
  /** 0 means "unlimited" (up to the number of options), like Baileys. */
  selectableCount: number;
}

export interface PollVoteBuildInput {
  pollCreationKey: WAMessageKey;
  pollEncKey: Uint8Array;
  optionNames: string[];
  /** Normalized JID of this connector account (author of the vote). */
  meJid: string;
  senderTimestampMs?: number;
  /** Injectable for deterministic tests; random when omitted. */
  iv?: Uint8Array;
}

export interface CapturedPollVote {
  voterJid: string;
  fromMe: boolean;
  senderTimestampMs: number;
  selectedHashes: string[];
}

export interface StoredPollUpdate {
  key: WAMessageKey;
  content: unknown;
}

export interface PollOptionResult {
  name: string;
  count: number;
  selectedByMe: boolean;
}

export interface AggregatePollResult {
  options: PollOptionResult[];
  totalVoters: number;
  capturedVotes: number;
}

export type PollAvailability = 'local_full' | 'local_partial' | 'unavailable';

export interface PollResultsEntry {
  pollMessageId: string;
  question: string | null;
  selectableCount: number | null;
  available: boolean;
  availability: PollAvailability;
  reason: string | null;
  totalVoters: number;
  capturedVotes: number;
  decryptionFailures: number;
  options: PollOptionResult[];
}

function storedMessageToContent(value: unknown): WAMessageContent | undefined {
  return value && typeof value === 'object' ? (value as WAMessageContent) : undefined;
}

function bytesFromStored(value: unknown): Uint8Array | null {
  if (value instanceof Uint8Array) return value;
  if (Array.isArray(value) && value.every(item => typeof item === 'number'))
    return new Uint8Array(value);
  if (typeof value === 'string' && value.length)
    return new Uint8Array(Buffer.from(value, 'base64'));
  if (value && typeof value === 'object') {
    const tagged = value as { type?: unknown; data?: unknown };
    if (tagged.type === 'Buffer' && Array.isArray(tagged.data))
      return new Uint8Array(tagged.data as number[]);
  }
  return null;
}

function coerceSenderTimestampMs(value: unknown): number {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'bigint') return Number(value);
  if (typeof value === 'string' && value.trim().length) {
    const numeric = Number(value);
    if (Number.isFinite(numeric)) return numeric;
  }
  if (value && typeof value === 'object') {
    const long = value as { low?: unknown; high?: unknown; unsigned?: unknown };
    if (typeof long.low === 'number' && typeof long.high === 'number') {
      const bits = (BigInt(long.high >>> 0) << 32n) | BigInt(long.low >>> 0);
      const signed = long.unsigned === false ? BigInt.asIntN(64, bits) : bits;
      const ms = Number(signed);
      if (Number.isFinite(ms) && ms >= 0) return ms;
    }
  }
  return 0;
}

/** Extract question/options/selectableCount from any poll creation variant (V1/V2/V3/V5). */
export function parsePollCreationContent(storedMessage: unknown): PollCreationDetails | null {
  const normalized = normalizeMessageContent(storedMessageToContent(storedMessage));
  if (!normalized) return null;
  const creation =
    normalized.pollCreationMessage ??
    normalized.pollCreationMessageV2 ??
    normalized.pollCreationMessageV3 ??
    normalized.pollCreationMessageV5;
  if (!creation) return null;
  const options = (creation.options ?? [])
    .map(option => String(option?.optionName ?? ''))
    .filter(option => option.length > 0);
  if (!options.length) return null;
  const rawCount = Number(
    (creation as { selectableOptionsCount?: unknown }).selectableOptionsCount ?? 0
  );
  const selectableCount =
    Number.isFinite(rawCount) && rawCount >= 1 ? Math.min(Math.floor(rawCount), options.length) : 0;
  return { question: String(creation.name ?? ''), options, selectableCount };
}

/**
 * The poll encKey equals the creation message's messageSecret. For polls this
 * account created it is inside the persisted raw payload (Baileys writes it
 * into the content before sending); some inbound 1:1 copies carry it too.
 * Group polls only have it when the sender key chain was captured, hence the
 * honest availability contract instead of guessing.
 */
export function pollEncKeyFromStoredMessage(storedMessage: unknown): Uint8Array | null {
  const raw = storedMessageToContent(storedMessage);
  if (!raw) return null;
  const topSecret = bytesFromStored(
    (raw as { messageContextInfo?: { messageSecret?: unknown } }).messageContextInfo?.messageSecret
  );
  if (topSecret && topSecret.length === 32) return topSecret;
  const normalized = normalizeMessageContent(raw);
  for (const variant of [
    normalized?.pollCreationMessage,
    normalized?.pollCreationMessageV2,
    normalized?.pollCreationMessageV3,
    normalized?.pollCreationMessageV5,
  ]) {
    const secret = bytesFromStored(
      (variant as { messageContextInfo?: { messageSecret?: unknown } } | undefined)
        ?.messageContextInfo?.messageSecret
    );
    if (secret && secret.length === 32) return secret;
  }
  return null;
}

/** Decrypt raw captured pollUpdateMessage payloads; never throws per-vote. */
export function decryptCapturedPollVotes(
  rows: StoredPollUpdate[],
  context: { pollMsgId: string; pollEncKey: Uint8Array; meJid: string | null }
): { votes: CapturedPollVote[]; undecryptable: number } {
  const votes: CapturedPollVote[] = [];
  let undecryptable = 0;
  for (const row of rows) {
    const normalized = normalizeMessageContent(storedMessageToContent(row.content));
    const update = normalized?.pollUpdateMessage;
    const encPayload = bytesFromStored(update?.vote?.encPayload);
    const encIv = bytesFromStored(update?.vote?.encIv);
    if (!update || !encPayload || !encIv) {
      undecryptable += 1;
      continue;
    }
    const fromMe = row.key.fromMe === true;
    if (fromMe && !context.meJid) {
      undecryptable += 1;
      continue;
    }
    const meId = context.meJid || 'me';
    const creationKey = (update.pollCreationMessageKey ?? undefined) as WAMessageKey | undefined;
    const voterJids = [
      ...new Set(
        [row.key.participant, getKeyAuthor(row.key, meId)].filter((jid): jid is string => !!jid)
      ),
    ];
    const creatorJids = [
      ...new Set(
        [creationKey?.participant, getKeyAuthor(creationKey, meId)].filter(
          (jid): jid is string => !!jid
        )
      ),
    ];
    try {
      let decrypted: ReturnType<typeof decryptPollVote> | undefined;
      let voterJid = '';
      for (const creator of creatorJids) {
        for (const voter of voterJids) {
          try {
            decrypted = decryptPollVote(
              { encPayload, encIv },
              {
                pollCreatorJid: creator,
                pollMsgId: String(update.pollCreationMessageKey?.id ?? context.pollMsgId),
                pollEncKey: context.pollEncKey,
                voterJid: voter,
              }
            );
            voterJid = voter;
            break;
          } catch {
            /* Try the alternate PN/LID identity. */
          }
        }
        if (decrypted) break;
      }
      if (!decrypted) throw new Error('Vote could not be decrypted with known identities');
      votes.push({
        voterJid,
        fromMe,
        senderTimestampMs: coerceSenderTimestampMs(update.senderTimestampMs),
        selectedHashes: (decrypted.selectedOptions ?? []).map(option =>
          Buffer.from(option).toString('hex')
        ),
      });
    } catch {
      undecryptable += 1;
    }
  }
  return { votes, undecryptable };
}

/** Latest complete vote per voter wins (WhatsApp semantics for re-voting). */
export function aggregateCapturedPollVotes(
  details: PollCreationDetails,
  votes: CapturedPollVote[]
): AggregatePollResult {
  const latestByVoter = new Map<string, CapturedPollVote>();
  for (const vote of votes) {
    const previous = latestByVoter.get(vote.voterJid);
    if (!previous || vote.senderTimestampMs >= previous.senderTimestampMs)
      latestByVoter.set(vote.voterJid, vote);
  }
  const hashToIndex = new Map(
    details.options.map((name, index) => [
      Buffer.from(sha256(Buffer.from(name))).toString('hex'),
      index,
    ])
  );
  const counts = details.options.map(() => 0);
  const selectedByMe = details.options.map(() => false);
  for (const vote of latestByVoter.values()) {
    for (const hash of vote.selectedHashes) {
      const index = hashToIndex.get(hash);
      if (index === undefined) continue;
      counts[index] += 1;
      if (vote.fromMe) selectedByMe[index] = true;
    }
  }
  return {
    options: details.options.map((name, index) => ({
      name,
      count: counts[index],
      selectedByMe: selectedByMe[index],
    })),
    totalVoters: [...latestByVoter.values()].filter(vote => vote.selectedHashes.length > 0).length,
    capturedVotes: votes.length,
  };
}

/**
 * Exact-match option validation. The app forwards user selections untouched,
 * so we must NOT trim: any string differing by whitespace is invalid.
 */
export function validatePollVoteSelection(
  details: PollCreationDetails,
  requested: unknown
): string[] {
  const invalid = (message: string, extra: Record<string, unknown> = {}): never => {
    throw new CapabilityError('INVALID_CAPABILITY_INPUT', message, {
      validOptions: details.options,
      ...extra,
    });
  };
  if (!Array.isArray(requested)) invalid('options must be an array of exact option names');
  const names = requested as unknown[];
  for (const name of names) {
    if (typeof name !== 'string' || name.trim().length === 0)
      invalid('options must contain non-empty strings');
  }
  const exact = names.map(name => name as string);
  if (new Set(exact).size !== exact.length) invalid('options must not repeat the same option');
  const known = new Set(details.options);
  const unknown = exact.filter(name => !known.has(name));
  if (unknown.length) invalid(`Unknown poll option: ${JSON.stringify(unknown[0])}`, { unknown });
  const max = details.selectableCount >= 1 ? details.selectableCount : details.options.length;
  if (exact.length > max)
    invalid(`This poll allows at most ${max} option(s)`, { maxSelectable: max });
  return exact;
}

/**
 * Mirror of Baileys' exported decryptPollVote, so its own decryption (and any
 * future upstream path) can read what we send.
 */
function buildForkPollVoteContent(input: PollVoteBuildInput): WAMessageContent {
  const pollMsgId = String(input.pollCreationKey.id ?? '');
  if (!pollMsgId)
    throw new CapabilityError('INVALID_CAPABILITY_INPUT', 'Poll creation message id is required');
  if (!input.meJid)
    throw new CapabilityError('INVALID_CAPABILITY_INPUT', 'Account JID is required to sign a vote');
  if (!Array.isArray(input.optionNames))
    throw new CapabilityError('INVALID_CAPABILITY_INPUT', 'Option names must be an array');
  const creatorJid = getKeyAuthor(input.pollCreationKey, input.meJid);
  const sign = Buffer.concat([
    Buffer.from(pollMsgId),
    Buffer.from(creatorJid),
    Buffer.from(input.meJid),
    Buffer.from('Poll Vote'),
    new Uint8Array([1]),
  ]);
  const key0 = hmacSign(Buffer.from(input.pollEncKey), new Uint8Array(32), 'sha256');
  const voteKey = hmacSign(sign, key0, 'sha256');
  const aad = Buffer.from(`${pollMsgId}\u0000${input.meJid}`);
  const plaintext = proto.Message.PollVoteMessage.encode({
    selectedOptions: input.optionNames.map(name => new Uint8Array(sha256(Buffer.from(name)))),
  }).finish();
  const iv = input.iv ?? randomBytes(8);
  const encPayload = aesEncryptGCM(plaintext, voteKey, iv, aad);
  return {
    pollUpdateMessage: {
      pollCreationMessageKey: {
        remoteJid: input.pollCreationKey.remoteJid,
        fromMe: input.pollCreationKey.fromMe,
        id: pollMsgId,
        ...(input.pollCreationKey.participant
          ? { participant: input.pollCreationKey.participant }
          : {}),
      },
      vote: { encPayload, encIv: iv },
      senderTimestampMs: input.senderTimestampMs ?? Date.now(),
    },
  };
}
/** Supports the production identity pair and the fork's stored-key input. */
export function buildPollVoteContent(input: PollVoteBuild | PollVoteBuildInput): WAMessageContent {
  return 'creationKey' in input
    ? buildProductionPollVoteContent(input)
    : buildForkPollVoteContent(input);
}
