#!/usr/bin/env tsx

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { SOCIAL_TOOL_REGISTRY } from '../mcp-server/src/mcp/tool-registry';

const root = resolve(__dirname, '..');
const outputPath = resolve(root, 'contracts/socialmedia-tools.json');
const generatedDocumentationPath = resolve(root, 'contracts/socialmedia-tools.md');
const generatedTypeScriptPath = resolve(root, 'mcp-server/src/mcp/contract.generated.ts');
const kubernetesManifestPath = resolve(root, 'k8s/base/manifest.yaml');
const check = process.argv.includes('--check');

function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`;
  if (value && typeof value === 'object') {
    const object = value as Record<string, unknown>;
    return `{${Object.keys(object)
      .sort()
      .map(key => `${JSON.stringify(key)}:${stableJson(object[key])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

const tools = SOCIAL_TOOL_REGISTRY.map(({ handler: _handler, ...definition }) => definition).sort(
  (left, right) => left.name.localeCompare(right.name)
);

const digest = `sha256:${createHash('sha256').update(stableJson(tools)).digest('hex')}`;
const contract = {
  schemaVersion: '2.0',
  service: 'socialmedia',
  digestAlgorithm: 'sha256',
  digest,
  tools,
};
const rendered = `${JSON.stringify(contract, null, 2)}\n`;
const markdownCell = (value: unknown) => String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const renderedDocumentation =
  `# Socialmedia tools\n\n` +
  `Generated by \`scripts/generate-socialmedia-contract.ts\` from the canonical registry. ` +
  `Do not edit this file directly.\n\n` +
  `Contract digest: \`${digest}\`\n\n` +
  `| Tool | Title | Effect | Auth scope | Capability |\n` +
  `|---|---|---|---|---|\n` +
  tools
    .map(
      definition =>
        `| \`${markdownCell(definition.name)}\` | ${markdownCell(
          definition.title
        )} | \`${markdownCell(definition.effect)}\` | \`${markdownCell(
          definition.authScope
        )}\` | \`${markdownCell(definition.capability)}\` |`
    )
    .join('\n') +
  `\n`;
const renderedTypeScript =
  `// Generated by scripts/generate-socialmedia-contract.ts. Do not edit.\n` +
  `export const SOCIALMEDIA_CONTRACT_DIGEST =\n` +
  `  '${digest}';\n`;
const digestAnnotationPattern = /(contracts\.e-dani\.com\/socialmedia-digest:\s*")[^"]+(")/g;

function readOrEmpty(path: string): string {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
}

function renderedKubernetesManifest(): string {
  const current = readOrEmpty(kubernetesManifestPath);
  const matches = [...current.matchAll(digestAnnotationPattern)];
  if (matches.length !== 2) {
    throw new Error(
      `Expected exactly two Socialmedia digest annotations in ${kubernetesManifestPath}; found ${matches.length}`
    );
  }
  return current.replace(digestAnnotationPattern, `$1${digest}$2`);
}

if (check) {
  const contractCurrent = readOrEmpty(outputPath);
  const documentationCurrent = readOrEmpty(generatedDocumentationPath);
  const typeScriptCurrent = readOrEmpty(generatedTypeScriptPath);
  const kubernetesCurrent = readOrEmpty(kubernetesManifestPath);
  const kubernetesExpected = renderedKubernetesManifest();
  if (
    contractCurrent !== rendered ||
    documentationCurrent !== renderedDocumentation ||
    typeScriptCurrent !== renderedTypeScript ||
    kubernetesCurrent !== kubernetesExpected
  ) {
    process.stderr.write(
      `Socialmedia contract artifacts are stale. Run: pnpm contract:generate\nExpected ${digest}\n`
    );
    process.exit(1);
  }
  process.stdout.write(`Socialmedia contract OK: ${digest} (${tools.length} tools)\n`);
} else {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, rendered);
  writeFileSync(generatedDocumentationPath, renderedDocumentation);
  writeFileSync(generatedTypeScriptPath, renderedTypeScript);
  writeFileSync(kubernetesManifestPath, renderedKubernetesManifest());
  process.stdout.write(`Wrote ${outputPath}: ${digest} (${tools.length} tools)\n`);
}
