#!/usr/bin/env python3
"""Render the per-account connector workloads from the account registry.

ADR 0001, decision 5: the Baileys (WhatsApp) and Telegram connector workloads
are GENERATED from k8s/base/social-accounts.json. Adding an account is: add a
registry entry, run this script, commit both files.

Outputs (both checked in, both under k8s/base/generated/):
  connectors.yaml       Deployments/Services/PVCs/LAN IngressRoutes per account
  social-accounts.json  the registry WITHOUT the `deploy` blocks: this is what
                        the `social-accounts` ConfigMap ships to mcp-server, so
                        deployment knobs never reach the runtime config.

Per-account knobs live in an optional `deploy` object on each registry entry;
every key has a default derived from accountId (see WHATSAPP_DEFAULTS /
TELEGRAM_DEFAULTS). Entries with `"enabled": false` render nothing. Instagram
entries render nothing (one shared Graph API connector, hand-written).

What stays hand-written (manifest.yaml / prod overlay), on purpose:
  - whatsapp-public IngressRoute (edge + SSO + /api/public deny + IG callback)
  - image pins (overlay images:/patch-image.yaml) and rollout flags such as
    CREDENTIAL_STORE_ENABLED (patch-credential-store.yaml): release concerns,
    not account shape.

Security note on `allowWebRenew`: it enables an UNAUTHENTICATED POST
/qr/renew. Only turn it on for accounts whose QR page is LAN-only; the
personal connector is public (whatsapp.e-dani.com) and must keep it off.

Usage:
  python3 scripts/render-connectors.py          # (re)write generated files
  python3 scripts/render-connectors.py --check  # exit 1 if they are stale
"""
import argparse
import copy
import json
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "k8s/base/social-accounts.json"
OUT_DIR = REPO / "k8s/base/generated"
OUT_MANIFEST = OUT_DIR / "connectors.yaml"
OUT_REGISTRY = OUT_DIR / "social-accounts.json"

NAMESPACE = "whatsapp-mcp"
SVC = f"{NAMESPACE}.svc.cluster.local"
HEADER = (
    "# GENERATED by scripts/render-connectors.py from k8s/base/social-accounts.json"
    " — do not edit\n"
)

WA_IMAGE = (
    "harbor.e-dani.com/homelab/whatsappmcp-whatsapp-connector:1357057afaf6"
    "@sha256:6a0789feb3fe2b268659508bbab259cfdf4a997513f83bc58fa181245aa67aae"
)
TG_CONNECTOR_IMAGE = "harbor.e-dani.com/homelab/whatsappmcp-telegram-connector:latest"
TG_SYNC_IMAGE = "harbor.e-dani.com/homelab/whatsappmcp-telegram-sync:latest"

ID_RE = re.compile(r"^[a-z][a-z0-9_-]*$")


def _env(name, value):
    return {"name": name, "value": value}


def _secret_env(name, secret, key):
    return {"name": name, "valueFrom": {"secretKeyRef": {"name": secret, "key": key}}}


# Storage envs shared by every connector that touches media (order matters:
# the $(VAR) references resolve against envFrom and earlier entries).
S3_ENV = [
    _env("S3_ENDPOINT", "http://skirmshop-drive-s3.backup-hub.svc.cluster.local:9000"),
    _env("S3_BUCKET", "skirmshop-drive"),
    _env("S3_REGION", "us-east-1"),
    _env("S3_PREFIX", "socialmedia"),
    _secret_env("AWS_ACCESS_KEY_ID", "skirmshop-drive-s3-socialmedia", "AWS_ACCESS_KEY_ID"),
    _secret_env("AWS_SECRET_ACCESS_KEY", "skirmshop-drive-s3-socialmedia", "AWS_SECRET_ACCESS_KEY"),
    _env("LEGACY_MINIO_ENDPOINT", f"whatsapp-mcp-minio.{SVC}:9000"),
    _env("LEGACY_MINIO_ACCESS_KEY", "$(MINIO_ROOT_USER)"),
    _env("LEGACY_MINIO_SECRET_KEY", "$(MINIO_ROOT_PASSWORD)"),
    _env("LEGACY_MINIO_USE_SSL", "false"),
    _env("LEGACY_MINIO_BUCKET", "socialmedia-media"),
    _env("MINIO_ENDPOINT", f"whatsapp-mcp-minio.{SVC}:9000"),
    _env("MINIO_ACCESS_KEY", "$(MINIO_ROOT_USER)"),
    _env("MINIO_SECRET_KEY", "$(MINIO_ROOT_PASSWORD)"),
    _env("MINIO_USE_SSL", "false"),
    _env("MINIO_BUCKET", "socialmedia-media"),
]
NATS_ENV = _env("NATS_URL", f"nats://whatsapp-mcp-nats.{SVC}:4222")
DB_ENV = _env(
    "DATABASE_URL",
    "postgresql://$(DB_USER):$(DB_PASSWORD)@postgres-shared-rw.databases.svc.cluster.local:5432/whatsappmcp",
)
SECRETS_ENV_FROM = [{"secretRef": {"name": "whatsapp-mcp-secrets"}}]


def _meta(name):
    return {"name": name, "namespace": NAMESPACE}


def _service(name, port):
    return {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": _meta(name),
        "spec": {
            "selector": {"app": name},
            "ports": [{"name": "http", "port": port, "targetPort": port}],
        },
    }


def _deployment(name, pod_spec):
    return {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": _meta(name),
        "spec": {
            "replicas": 1,
            "strategy": {"type": "Recreate"},
            "selector": {"matchLabels": {"app": name}},
            "template": {"metadata": {"labels": {"app": name}}, "spec": pod_spec},
        },
    }


# ── WhatsApp (Baileys) ─────────────────────────────────────────────────────────
def whatsapp_defaults(account_id):
    lan_host = f"whatsapp-{account_id}.lan.e-dani.com"
    return {
        "name": f"whatsapp-connector-{account_id}",
        "sessionPvc": f"whatsapp-session-data-{account_id}",
        "sessionPvcSize": "1Gi",
        "storageClassName": "longhorn",
        # Baileys: WhatsApp flags datacenter IPs → residential `ubuntu` node;
        # the session PVC is Longhorn RWO (no CSI on the arm64 GPU nodes).
        "nodeSelector": {
            "topology": "lan",
            "kubernetes.io/hostname": "ubuntu",
            "kubernetes.io/arch": "amd64",
        },
        # false only for the legacy personal connector (events untagged).
        "connectorAccountEnv": True,
        "lanIngress": f"whatsapp-{account_id}-lan",
        "lanHost": lan_host,
        "qrPublicUrl": None,  # None → https://<lanHost>/qr/page
        # F1.7 honest voice: presign voice notes to S3 before the NATS emit.
        "emitAudioAttachments": False,
        "allowWebRenew": False,
        "env": [],  # extra env appended last
    }


def render_whatsapp(account):
    aid = account["accountId"]
    d = {**whatsapp_defaults(aid), **account.get("deploy", {})}
    name = d["name"]
    qr_url = d["qrPublicUrl"] or f"https://{d['lanHost']}/qr/page"
    env = [
        _secret_env("SHARED_VALKEY_SOCIALMEDIA_PASSWORD", "socialmedia-shared-valkey", "password"),
        _env(
            "REDIS_URL",
            "redis://socialmedia:$(SHARED_VALKEY_SOCIALMEDIA_PASSWORD)"
            "@shared-valkey-master.databases.svc.cluster.local:6379/0",
        ),
        NATS_ENV,
        DB_ENV,
        _env("ENABLE_SENDING", "true"),
        _env("SESSION_PATH", "/app/persistent-session"),
    ]
    if d["connectorAccountEnv"]:
        env.append(_env("CONNECTOR_ACCOUNT", aid))
    env.append(_env("WA_QR_PUBLIC_URL", qr_url))
    if d["emitAudioAttachments"]:
        env += [
            _env("WA_EMIT_AUDIO_ATTACHMENTS", "true"),
            _env("S3_PUBLIC_ENDPOINT", "https://skirmshop-s3.e-dani.com"),
            _env("S3_PRESIGN_EXPIRY_SECONDS", "3600"),
        ]
    env += S3_ENV
    env += [
        _env("EMBEDDING_BASE_URL", "http://bge-m3-embedding.llm.svc.cluster.local:8000/v1"),
        _env("EMBEDDING_MODEL", "bge-m3"),
        _env("EMBEDDING_DIMENSION", "1024"),
    ]
    if d["allowWebRenew"]:
        # First, not last: it used to arrive via an overlay strategic-merge
        # patch, which prepends; keeping the position keeps the live pod spec
        # unchanged (no rollout of the paired Baileys sessions).
        env.insert(0, _env("ALLOW_WEB_RENEW", "true"))
    env += d["env"]

    pvc = {
        "apiVersion": "v1",
        "kind": "PersistentVolumeClaim",
        "metadata": _meta(d["sessionPvc"]),
        "spec": {
            "accessModes": ["ReadWriteOnce"],
            "resources": {"requests": {"storage": d["sessionPvcSize"]}},
            "storageClassName": d["storageClassName"],
        },
    }
    deployment = _deployment(
        name,
        {
            "enableServiceLinks": False,
            "nodeSelector": d["nodeSelector"],
            "containers": [
                {
                    "name": name,
                    "image": WA_IMAGE,
                    "ports": [{"name": "http", "containerPort": 3001}],
                    "env": env,
                    "envFrom": SECRETS_ENV_FROM,
                    "resources": {
                        "requests": {"cpu": "50m", "memory": "128Mi"},
                        "limits": {"memory": "512Mi"},
                    },
                    "readinessProbe": {
                        "httpGet": {"path": "/api/v1/health", "port": 3001},
                        "initialDelaySeconds": 15,
                        "timeoutSeconds": 3,
                    },
                    "volumeMounts": [
                        {"name": d["sessionPvc"], "mountPath": "/app/persistent-session"}
                    ],
                }
            ],
            "volumes": [
                {"name": d["sessionPvc"], "persistentVolumeClaim": {"claimName": d["sessionPvc"]}}
            ],
        },
    )
    host = d["lanHost"]
    backend = [{"name": name, "port": 3001}]
    lan = {
        "apiVersion": "traefik.io/v1alpha1",
        "kind": "IngressRoute",
        "metadata": _meta(d["lanIngress"]),
        "spec": {
            "entryPoints": ["websecure"],
            "routes": [
                {
                    "match": f"Host(`{host}`) && PathPrefix(`/api/public`)",
                    "kind": "Rule",
                    "middlewares": [{"name": "connector-public-api-deny", "namespace": NAMESPACE}],
                    "services": backend,
                },
                {"match": f"Host(`{host}`)", "kind": "Rule", "services": copy.deepcopy(backend)},
            ],
            "tls": {"store": {"name": "default", "namespace": "traefik-lan"}},
        },
    }
    _expect_url(account, "connectorUrl", f"http://{name}.{SVC}:3001")
    return [pvc, deployment, _service(name, 3001), lan]


# ── Telegram (connector + session-less sync) ───────────────────────────────────
def telegram_defaults(account_id):
    return {
        "connectorName": f"telegram-connector-{account_id}",
        "syncName": f"telegram-sync-{account_id}",
        "connectorAccountEnv": True,
        # Secret key holding this account's gramjs session; None → the
        # TELEGRAM_SESSION_STRING already loaded by envFrom (personal).
        "sessionSecretKey": f"TELEGRAM_SESSION_STRING_{account_id.upper().replace('-', '_')}",
        "connectorMemoryLimit": "768Mi",
        "syncMemoryLimit": "3Gi",
        "connectorNodeSelector": {"topology": "lan", "kubernetes.io/arch": "amd64"},
        # telegram-sync is SESSION-LESS (ingests via NATS + the connector HTTP
        # API) → no IP binding → OVH edge node sauvage (role=edge taint).
        "syncNodeSelector": {"kubernetes.io/hostname": "sauvage", "kubernetes.io/arch": "amd64"},
        "syncTolerations": [
            {"key": "role", "operator": "Equal", "value": "edge", "effect": "NoSchedule"}
        ],
    }


def render_telegram(account):
    aid = account["accountId"]
    d = {**telegram_defaults(aid), **account.get("deploy", {})}
    cname, sname = d["connectorName"], d["syncName"]

    c_env = [NATS_ENV]
    if d["connectorAccountEnv"]:
        c_env.append(_env("CONNECTOR_ACCOUNT", aid))
    if d["sessionSecretKey"]:
        c_env.append(
            _secret_env("TELEGRAM_SESSION_STRING", "whatsapp-mcp-secrets", d["sessionSecretKey"])
        )
    connector = _deployment(
        cname,
        {
            "enableServiceLinks": False,
            "nodeSelector": d["connectorNodeSelector"],
            "containers": [
                {
                    "name": "telegram-connector",
                    "image": TG_CONNECTOR_IMAGE,
                    "ports": [{"name": "http", "containerPort": 3002}],
                    "livenessProbe": {
                        "httpGet": {"path": "/health", "port": 3002},
                        "initialDelaySeconds": 60,
                        "periodSeconds": 30,
                        "timeoutSeconds": 10,
                        "failureThreshold": 4,
                    },
                    "env": c_env,
                    "envFrom": SECRETS_ENV_FROM,
                    "resources": {
                        "requests": {"cpu": "30m", "memory": "256Mi"},
                        "limits": {"memory": d["connectorMemoryLimit"]},
                    },
                }
            ],
        },
    )

    s_env = [NATS_ENV, DB_ENV]
    if d["connectorAccountEnv"]:
        s_env.append(_env("CONNECTOR_ACCOUNT", aid))
    s_env.append(_env("CONNECTOR_BASE_URL", f"http://{cname}.{SVC}:3002"))
    s_env += S3_ENV
    sync_spec = {
        "enableServiceLinks": False,
        "nodeSelector": d["syncNodeSelector"],
        "containers": [
            {
                "name": "telegram-sync",
                "image": TG_SYNC_IMAGE,
                "ports": [{"name": "http", "containerPort": 3080}],
                "env": s_env,
                "envFrom": SECRETS_ENV_FROM,
                "resources": {
                    "requests": {"cpu": "100m", "memory": "1Gi"},
                    "limits": {"memory": d["syncMemoryLimit"]},
                },
                "readinessProbe": {
                    "httpGet": {"path": "/health", "port": 3080},
                    "initialDelaySeconds": 10,
                    "periodSeconds": 10,
                    "timeoutSeconds": 3,
                },
            }
        ],
    }
    if d["syncTolerations"]:
        sync_spec["tolerations"] = d["syncTolerations"]
    sync = _deployment(sname, sync_spec)

    _expect_url(account, "connectorUrl", f"http://{cname}.{SVC}:3002")
    _expect_url(account, "bridgeUrl", f"http://{sname}.{SVC}:3080")
    return [connector, _service(cname, 3002), sync, _service(sname, 3080)]


RENDERERS = {"whatsapp": render_whatsapp, "telegram": render_telegram}


def _expect_url(account, field, expected):
    got = account.get(field)
    if got is not None and got.rstrip("/") != expected:
        raise SystemExit(
            f"{account['channel']}:{account['accountId']}: {field} {got!r} does not point at "
            f"the generated Service ({expected!r})"
        )


def render(accounts):
    """Return (connectors_yaml, runtime_registry_json) for a registry list."""
    docs = []
    names = set()
    for account in accounts:
        aid = account.get("accountId", "")
        if not ID_RE.match(aid):
            raise SystemExit(f"invalid accountId {aid!r}")
        if account.get("enabled", True) is False:
            continue
        renderer = RENDERERS.get(account["channel"])
        if renderer is None:
            continue
        group = renderer(account)
        for doc in group:
            key = (doc["kind"], doc["metadata"]["name"])
            if key in names:
                raise SystemExit(f"{account['channel']}:{aid}: duplicate {key[0]}/{key[1]}")
            names.add(key)
        docs.append((f"{account['channel']}:{aid} — {account.get('label', aid)}", group))

    out = [HEADER]
    for title, group in docs:
        out.append(f"# ── {title} ──\n")
        for doc in group:
            out.append("---\n")
            out.append(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=1000))
    runtime = [{k: v for k, v in a.items() if k != "deploy"} for a in accounts]
    return "".join(out), json.dumps(runtime, indent=2, ensure_ascii=False) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args(argv)

    accounts = json.loads(REGISTRY.read_text(encoding="utf-8"))
    manifest, runtime = render(accounts)
    outputs = {OUT_MANIFEST: manifest, OUT_REGISTRY: runtime}

    if args.check:
        stale = [
            p for p, text in outputs.items()
            if not p.exists() or p.read_text(encoding="utf-8") != text
        ]
        for p in stale:
            print(f"STALE: {p.relative_to(REPO)} — run python3 scripts/render-connectors.py",
                  file=sys.stderr)
        return 1 if stale else 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for p, text in outputs.items():
        p.write_text(text, encoding="utf-8")
        print(f"wrote {p.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
